inherit_from:
  - https://raw.githubusercontent.com/trinistr/rubocop-config/main/rubocop.yml

plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety
  - rubocop-yard

Gemspec/DevelopmentDependencies:
  # I want to increase visibility of the dependency, without strictly requiring it.
  AllowedGems:
    - vector_number
