#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate an image from dicey results.
# Requires gnuplot to be installed and in PATH.
# Usage: dicey 6 6 6 -f gnuplot | gnuplot-for-dicey

require "tempfile"

data = ARGF.read
description = data[/(?<=\A# ).+$/] || "dice"
Tempfile.create do |file|
  file << data
  file.flush
  Process.wait(
    Process.spawn(
      "gnuplot",
      "-e", "set term pngcairo size 1000,600",
      "-e", %(set output "#{description}.png"),
      "-e", "set boxwidth 0.9 relative",
      "-e", "set style fill solid 0.5",
      "-e", "plot [][0:] \"#{file.path}\" " \
            "using 1:2:xticlabels(1) with boxes title \"#{description}\", " \
            "'' using 1:2:2 with labels notitle"
    )
  )
end
