name: CRuby
permissions:
  contents: read
on:
  workflow_call:
jobs:
  test:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        - "3.0.0"
        - "3.0"
        - "3.1"
        - "3.2"
        - "3.3"
        - "3.4"
        - "head"
        experimental: [false]
        include:
          - ruby: "3.0.0"
            rubygems: "3.3.26"
          - ruby: "3.0"
            rubygems: "3.3.26"
          - ruby: "3.1"
            rubygems: "3.3.26"
    continue-on-error: ${{ matrix.experimental }}
    env:
      BUNDLE_ONLY: "default:test"
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        rubygems: ${{ matrix.rubygems || 'default' }}
        bundler: latest
        bundler-cache: true
    - name: Run RSpec
      run: bundle exec rake spec
